name: NAT-Lobby
version: '1.0'
main: fr.Nat0uille.NATLobby.Main
api-version: '1.21'
load: STARTUP
authors: [ Nat0uille ]
commands:
  spawn:
    aliases: sp
    usage: /<command>
  setspawn:
    usage: /<command>